// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytwncscfqkfemwefvxck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0d25jc2NmcWtmZW13ZWZ2eGNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDk2NTEsImV4cCI6MjA2ODU4NTY1MX0.qhQyStmfHSLVaj6LjO3IRkwJYGPMbpy3jzDK4lu-Ot0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});